.coafile: Add YAMLLintBear
coala-analyzer/coala-vim pull request #32
Opened 2017-06-27 05:58 UTC by khanchi97

Add YAMLLintBear for fixing issues with .yml files

Fixes https://github.com/coala/coala-vim/issues/31

2017-06-27 11:24 UTC, hemangsk requested changes

2017-06-27 11:24 UTC, hemangsk commented on .coafile
> +bears = YAMLLintBears
YAMLLintBear*

2017-06-27 11:28 UTC, khanchi97 commented on .coafile
> +bears = YAMLLintBears
what i should do ?
1. modify it and make another PR
2. you want to suggest.

2017-06-27 11:32 UTC, hemangsk commented on .coafile
> +bears = YAMLLintBears
You can do modifications to commit, and in this PR only. Please have a look on the process here http://api.coala.io/en/latest/Developers/Git_Basics.html#follow-up  :) 👍

2017-06-27 11:32 UTC, hemangsk commented on .coafile
> +bears = YAMLLintBears
Marking ```work in progress```

2017-06-27 12:05 UTC, vidurkatyal commented
The issue reference line should say 'Closes' instead of 'Fixes' as this commit is adding an enhancement.
Refer the [Writing Good Commits](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference) guide. :smile:

2017-06-27 12:47 UTC, khanchi97 commented
thank you vidurkatyal

2017-06-28 05:25 UTC, vidurkatyal approved these changes

2017-06-28 05:39 UTC, vidurkatyal commented
ack 3b86a63a7c175f85185d9c08ecfb6e9d6f97b80c

2017-06-29 07:00 UTC, khanchi97 commented on .coafile
> +bears = YAMLLintBears
I have changed it.

2017-07-02 02:25 UTC, prachi1210 commented
LGTM 
ack 3b86a63

2017-07-02 18:46 UTC, SanketDG commented
@rultor merge

2017-07-02 18:48 UTC, rultor commented
> @rultor merge

@sanketdg OK, I'll try to merge now. You can check the progress of the merge [here](http://www.rultor.com/t/12234-312509632)

2017-07-02 18:48 UTC, merged

2017-07-02 18:50 UTC, rultor commented
> @rultor merge

@sanketdg Done! FYI, the full log is [here](http://www.rultor.com/t/12234-312509632) (took me 2min)